import {Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { ToastContainer } from "react-toastify";

const OutfitFont = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar></Navbar>
        <main className="container mx-auto">
           {children}
        </main>
           <ToastContainer />
       </body>
    </html>
  );
}
